export * from './objetivo'
export * from './historico'
export * from './julgamento'
export * from './licao'
export * from './linha-modelo'
export * from './mate-forcado'
export * from './forcado'
export * from './catalogo'
